name: Daily Subscription Expire Cron

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  expire-subscriptions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Указываем working-directory для поиска package.json в папке api
      - name: Install Dependencies
        working-directory: ./api
        run: npm install

      # Запускаем скрипт внутри папки api
      - name: Run Expire Script
        working-directory: ./api
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$SERVICE_ACCOUNT_KEY" > serviceAccountKey.json
          node expire-subscriptions.js
          rm -f serviceAccountKey.json
